/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResourceItem = IDL.Record({
  'tag' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ResourceCategory = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'items' : IDL.Vec(ResourceItem),
});
export const Time = IDL.Int;
export const CircleScore = IDL.Record({
  'timestamp' : Time,
  'percentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addItemToCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(ResourceCategory)], ['query']),
  'getTopCircleScores' : IDL.Func([IDL.Nat], [IDL.Vec(CircleScore)], ['query']),
  'submitCircleScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResourceItem = IDL.Record({
    'tag' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ResourceCategory = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'items' : IDL.Vec(ResourceItem),
  });
  const Time = IDL.Int;
  const CircleScore = IDL.Record({
    'timestamp' : Time,
    'percentage' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addItemToCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(ResourceCategory)], ['query']),
    'getTopCircleScores' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CircleScore)],
        ['query'],
      ),
    'submitCircleScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };