/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CircleScore { 'timestamp' : Time, 'percentage' : bigint }
export interface ResourceCategory {
  'name' : string,
  'description' : string,
  'items' : Array<ResourceItem>,
}
export interface ResourceItem {
  'tag' : string,
  'url' : string,
  'title' : string,
  'description' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addCategory' : ActorMethod<[string, string], undefined>,
  'addItemToCategory' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'getCategories' : ActorMethod<[], Array<ResourceCategory>>,
  'getTopCircleScores' : ActorMethod<[bigint], Array<CircleScore>>,
  'submitCircleScore' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];